### Recuperar todos los libros
GET http://localhost:1234/books

### Recuperar todos los libros por género y año
GET http://localhost:1234/books?genre=ciEncIa&year=2015

### Recuperar un libro por id
GET http://localhost:1234/books/6da6d5cd-6df0-43a5-a9ef-8e6b2f4774cb

### Crear un libro
POST http://localhost:1234/books
Content-Type: application/json

{
    "name": "El emperador pobre",
    "author": "Frank Solo",
    "genres": [
        "novela",
        "recetas",
        "filosofía"
    ],
    "description": "¿Es la ciencia contraria al cristianismo? Pues bien, en este libro se exploran las similitudes que hay entre la existencia de DIOS y la forma en que funciona la mecánica cuántica",
    "year": 2020
}

### Actualizar un libro
PATCH http://localhost:1234/books/6da6d5cd-6df0-43a5-a9ef-8e6b2f4774cb
Content-Type: application/json

{
    "year": 2009,
    "description": "Esta es otra descripción del libro actualizada por el método patch"
}

### Eliminar un libro
DELETE http://localhost:1234/books/61770f85-1583-4d1f-b361-f1a2aba26da5
Content-Type: application/json